"""empty message

Revision ID: 701f9102a4ba
Revises: 9b39daeffd6a
Create Date: 2023-08-18 00:46:33.126056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701f9102a4ba'
down_revision: Union[str, None] = '9b39daeffd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=30), nullable=False),
    sa.Column('quest', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('time', sa.String(length=30), nullable=False),
    sa.Column('guest_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=False),
    sa.Column('franchise', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
