"""empty message

Revision ID: a8d6d74d7d6b
Revises: d73cc9eae753
Create Date: 2023-08-31 14:09:08.400150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d6d74d7d6b'
down_revision: Union[str, None] = 'd73cc9eae753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'franchise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('franchise', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
