"""empty message

Revision ID: d73cc9eae753
Revises: 131564707680
Create Date: 2023-08-31 14:01:22.972327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73cc9eae753'
down_revision: Union[str, None] = '131564707680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'franchise_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'franchise_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
